from tkinter import *
root = Tk()
root.title('Shrift')
root.config(bg = 'grey')
root.geometry('450x570')
def f():
    print(entry.get())
    # entry.config(font=)
entry = Entry(root, width=30, font=('Broadway', 10))
button1 = Button(root, text='Lucida Sans', font=('Lucida Sans', 10))
button2 = Button(root, text='Broadway', font=('Broadway', 10))
button3 = Button(root, text='Dubai', font=('Dubai', 10))
button4 = Button(root, text='Castellar', font=('Castellar', 10))
button5 = Button(root, text='Edwardian Script ITC', font=('Edwardian Script ITC', 10))
button6 = Button(root, text='Blackadder ITC', font=('Blackadder ITC', 10))
entry.pack()
button1.pack()
button2.pack()
button3.pack()
button4.pack()
button5.pack()
button6.pack()

root.mainloop()
